import {
  DEFAULT_SEED,
  hexToArgb,
  schemeFromSeed,
  type MdScheme,
  type ThemeMode,
} from "./palette.ts";

export const SPACING = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 48,
} as const;

export const RADIUS = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 28,
  full: 9999,
} as const;

export const TYPE_SCALE = {
  displayLarge: { size: 57, line: 64, weight: 400, tracking: -0.25 },
  headlineLarge: { size: 32, line: 40, weight: 600, tracking: 0 },
  headlineMedium: { size: 28, line: 36, weight: 600, tracking: 0 },
  titleLarge: { size: 22, line: 28, weight: 500, tracking: 0 },
  titleMedium: { size: 16, line: 24, weight: 500, tracking: 0.15 },
  bodyLarge: { size: 16, line: 24, weight: 400, tracking: 0.15 },
  bodyMedium: { size: 14, line: 20, weight: 400, tracking: 0.25 },
  labelLarge: { size: 14, line: 20, weight: 500, tracking: 0.1 },
  labelMedium: { size: 12, line: 16, weight: 500, tracking: 0.5 },
  labelSmall: { size: 11, line: 16, weight: 500, tracking: 0.5 },
} as const;

export function kebab(key: string) {
  return key.replace(/([A-Z])/g, "-$1").toLowerCase();
}

function cssFromScheme(scheme: MdScheme, selector: string) {
  const lines = Object.entries(scheme).map(
    ([k, v]) => `  --md-${kebab(k)}: ${v};`,
  );
  return `${selector} {\n${lines.join("\n")}\n}`;
}

export function generateCss(seed = DEFAULT_SEED): string {
  const light = schemeFromSeed(seed, "light");
  const dark = schemeFromSeed(seed, "dark");
  const spacing = Object.entries(SPACING)
    .map(([k, v]) => `  --space-${k}: ${v}px;`)
    .join("\n");
  const radius = Object.entries(RADIUS)
    .map(([k, v]) => `  --radius-${k}: ${v}px;`)
    .join("\n");
  return `/* Generated by Britta Design. DO NOT EDIT. */
/* Seed ${seed} */

${cssFromScheme(light, ":root, [data-theme=light]")}

${cssFromScheme(dark, "[data-theme=dark]")}

:root {
${spacing}
${radius}
  --font-sans: Inter, ui-sans-serif, system-ui, sans-serif;
  --font-display: Outfit, var(--font-sans);
  --font-mono: "JetBrains Mono", ui-monospace, "SF Mono", Menlo, Consolas, monospace;
}
`;
}

function kotlinColorObject(name: string, scheme: MdScheme): string {
  const body = Object.entries(scheme)
    .map(([k, v]) => `    val ${k} = Color(${hexToArgb(v)})`)
    .join("\n");
  return `object ${name} {\n${body}\n}`;
}

export function generateKotlin(seed = DEFAULT_SEED, mode: ThemeMode = "light"): string {
  const light = schemeFromSeed(seed, "light");
  const dark = schemeFromSeed(seed, "dark");
  const spacing = Object.entries(SPACING)
    .map(([k, v]) => `    val ${k} = ${v}.dp`)
    .join("\n");
  const radius = Object.entries(RADIUS)
    .map(([k, v]) => `    val ${k} = ${v}.dp`)
    .join("\n");
  const type = Object.entries(TYPE_SCALE)
    .map(
      ([k, v]) => `    val ${k} = TextStyle(
        fontFamily = BrittaFontFamily,
        fontWeight = FontWeight.W${v.weight},
        fontSize = ${v.size}.sp,
        lineHeight = ${v.line}.sp,
        letterSpacing = ${v.tracking}.sp
    )`,
    )
    .join("\n\n");

  return `// Generated by Britta Design. DO NOT EDIT.
// Seed ${seed}
package com.britta.design.generated

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

val BrittaFontFamily = FontFamily.SansSerif

${kotlinColorObject("BrittaLightColors", light)}

${kotlinColorObject("BrittaDarkColors", dark)}

object BrittaGeneratedColors {
    // Active scheme snapshot (${mode})
${Object.entries(mode === "dark" ? dark : light)
  .map(([k, v]) => `    val ${k} = Color(${hexToArgb(v)})`)
  .join("\n")}
}

object BrittaGeneratedSpacing {
${spacing}
}

object BrittaGeneratedRadius {
${radius}
}

object BrittaGeneratedTypography {
${type}
}
`;
}

export function generateTokensJson(seed = DEFAULT_SEED): string {
  const light = schemeFromSeed(seed, "light");
  const dark = schemeFromSeed(seed, "dark");
  const color = (scheme: MdScheme) =>
    Object.fromEntries(
      Object.entries(scheme).map(([k, v]) => [k, { value: v, type: "color" }]),
    );
  return JSON.stringify(
    {
      $schema: "https://britta.design/tokens.schema.json",
      seed,
      color: { light: color(light), dark: color(dark) },
      spacing: Object.fromEntries(
        Object.entries(SPACING).map(([k, v]) => [
          k,
          { value: `${v}px`, type: "dimension" },
        ]),
      ),
      radius: Object.fromEntries(
        Object.entries(RADIUS).map(([k, v]) => [
          k,
          { value: `${v}px`, type: "dimension" },
        ]),
      ),
      typography: Object.fromEntries(
        Object.entries(TYPE_SCALE).map(([k, v]) => [
          k,
          {
            fontFamily: k.startsWith("display") || k.startsWith("headline") ? "Outfit" : "Inter",
            fontSize: `${v.size}px`,
            lineHeight: `${v.line}px`,
            fontWeight: v.weight,
          },
        ]),
      ),
    },
    null,
    2,
  );
}

/** Drop-in CSS framework: tokens + Tailwind-like utilities + component classes. */
export function generateStandaloneCss(seed = DEFAULT_SEED): string {
  const tokens = generateCss(seed);
  const light = schemeFromSeed(seed, "light");
  const colorUtils = Object.keys(light)
    .map((key) => {
      const k = kebab(key);
      return [
        `.b-bg-${k} { background-color: var(--md-${k}); }`,
        `.b-text-${k} { color: var(--md-${k}); }`,
        `.b-border-${k} { border-color: var(--md-${k}); }`,
      ].join("\n");
    })
    .join("\n");

  const spaceUtils = Object.entries(SPACING)
    .map(([k, v]) =>
      [
        `.b-p-${k} { padding: ${v}px; }`,
        `.b-px-${k} { padding-left: ${v}px; padding-right: ${v}px; }`,
        `.b-py-${k} { padding-top: ${v}px; padding-bottom: ${v}px; }`,
        `.b-m-${k} { margin: ${v}px; }`,
        `.b-gap-${k} { gap: ${v}px; }`,
      ].join("\n"),
    )
    .join("\n");

  const radiusUtils = Object.entries(RADIUS)
    .map(([k, v]) => `.b-rounded-${k} { border-radius: ${v}px; }`)
    .join("\n");

  const typeUtils = Object.entries(TYPE_SCALE)
    .map(
      ([k, v]) =>
        `.b-text-${kebab(k)} { font-size: ${v.size}px; line-height: ${v.line}px; font-weight: ${v.weight}; letter-spacing: ${v.tracking}px; }`,
    )
    .join("\n");

  return `${tokens}

/* Britta utilities — Tailwind-like, token-backed */
${colorUtils}
${spaceUtils}
${radiusUtils}
${typeUtils}

.b-flex { display: flex; }
.b-flex-col { display: flex; flex-direction: column; }
.b-items-center { align-items: center; }
.b-justify-center { justify-content: center; }
.b-justify-between { justify-content: space-between; }
.b-w-full { width: 100%; }
.b-font-sans { font-family: var(--font-sans); }
.b-font-display { font-family: var(--font-display); }
.b-font-mono { font-family: var(--font-mono); }

/* Component primitives */
.britta-button {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: var(--space-sm);
  min-height: 40px;
  padding: 0 var(--space-md);
  border: 0;
  border-radius: var(--radius-full);
  background: var(--md-primary);
  color: var(--md-on-primary);
  font: inherit;
  font-weight: 500;
  cursor: pointer;
}
.britta-button[data-variant="tonal"] {
  background: var(--md-primary-container);
  color: var(--md-on-primary-container);
}
.britta-button[data-variant="outlined"] {
  background: transparent;
  color: var(--md-primary);
  box-shadow: inset 0 0 0 1px var(--md-outline-variant);
}
.britta-button[data-variant="text"] {
  background: transparent;
  color: var(--md-primary);
}
.britta-button:focus-visible {
  outline: 3px solid var(--md-secondary);
  outline-offset: 2px;
}
.britta-button:disabled { opacity: 0.38; cursor: not-allowed; }

.britta-card {
  border-radius: var(--radius-lg);
  padding: var(--space-md);
  background: var(--md-surface-container-low);
  color: var(--md-on-surface);
}
.britta-card[data-variant="filled"] { background: var(--md-surface-container-highest); }
.britta-card[data-variant="outlined"] {
  background: var(--md-surface);
  box-shadow: inset 0 0 0 1px var(--md-outline-variant);
}

.britta-field {
  min-height: 56px;
  padding: 0 var(--space-md);
  border-radius: var(--radius-sm);
  box-shadow: inset 0 0 0 1px var(--md-outline-variant);
  background: transparent;
  color: var(--md-on-surface);
  font: inherit;
}
.britta-chip {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  height: 32px;
  padding: 0 12px;
  border-radius: var(--radius-sm);
  box-shadow: inset 0 0 0 1px var(--md-outline-variant);
  background: transparent;
  color: var(--md-on-surface-variant);
  font: inherit;
  font-size: 14px;
  font-weight: 500;
}
.britta-chip[data-selected="true"] {
  background: var(--md-secondary-container);
  color: var(--md-on-secondary-container);
  box-shadow: none;
}
.britta-fab {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 56px;
  height: 56px;
  border: 0;
  border-radius: var(--radius-lg);
  background: var(--md-primary-container);
  color: var(--md-on-primary-container);
  cursor: pointer;
}
`;
}
