import { composeIconName, type MdIconStyle } from "./icon";

export type IconCategory =
  | "actions"
  | "navigation"
  | "communication"
  | "media"
  | "places"
  | "ui"
  | "weather"
  | "devices"
  | "editor"
  | "finance"
  | "health"
  | "files"
  | "social"
  | "charts";

export type IconPackId =
  | "core"
  | "navigation"
  | "editor"
  | "media"
  | "devices"
  | "weather"
  | "finance"
  | "health"
  | "files"
  | "social"
  | "charts"
  | "graphics"
  | "travel";

export type IconEntry = {
  name: string;
  label: string;
  category: IconCategory;
  packs: IconPackId[];
};

function i(
  name: string,
  label: string,
  category: IconCategory,
  packs: IconPackId[],
): IconEntry {
  return { name, label, category, packs };
}

export const ICON_PACKS: {
  id: IconPackId;
  label: string;
  blurb: string;
  icon: string;
}[] = [
  { id: "core", label: "Core", blurb: "The 24 symbols every screen needs.", icon: "apps" },
  { id: "navigation", label: "Navigation", blurb: "App bars, drawers, and wayfinding.", icon: "near_me" },
  { id: "editor", label: "Editor", blurb: "Typography, alignment, and ink.", icon: "edit" },
  { id: "media", label: "Media", blurb: "Playback, capture, and volume.", icon: "play_arrow" },
  { id: "devices", label: "Devices", blurb: "Phones, wearables, and hardware.", icon: "devices" },
  { id: "weather", label: "Weather", blurb: "Sky, climate, and atmosphere.", icon: "partly_cloudy_day" },
  { id: "finance", label: "Finance", blurb: "Money, ledgers, and trends.", icon: "payments" },
  { id: "health", label: "Health", blurb: "Care, fitness, and wellbeing.", icon: "monitor_heart" },
  { id: "files", label: "Files", blurb: "Folders, documents, and cloud.", icon: "folder" },
  { id: "social", label: "Social", blurb: "Reactions, sharing, community.", icon: "thumb_up" },
  { id: "charts", label: "Charts", blurb: "Plots used by the graphics kit.", icon: "bar_chart" },
  { id: "graphics", label: "Graphics", blurb: "Filters, shaders, and light.", icon: "gradient" },
  { id: "travel", label: "Travel", blurb: "Transit, lodging, and maps.", icon: "flight" },
];

export const ICONS: IconEntry[] = [
  i("home", "Home", "navigation", ["core", "navigation"]),
  i("search", "Search", "actions", ["core"]),
  i("settings", "Settings", "ui", ["core"]),
  i("menu", "Menu", "navigation", ["core", "navigation"]),
  i("close", "Close", "actions", ["core"]),
  i("add", "Add", "actions", ["core"]),
  i("remove", "Remove", "actions", ["core"]),
  i("check", "Check", "actions", ["core"]),
  i("check_circle", "Check circle", "actions", ["core"]),
  i("cancel", "Cancel", "actions", ["core"]),
  i("edit", "Edit", "actions", ["core", "editor"]),
  i("delete", "Delete", "actions", ["core"]),
  i("share", "Share", "actions", ["core", "social"]),
  i("download", "Download", "actions", ["core", "files"]),
  i("upload", "Upload", "actions", ["core", "files"]),
  i("content_copy", "Copy", "actions", ["core", "editor"]),
  i("content_cut", "Cut", "actions", ["editor"]),
  i("content_paste", "Paste", "actions", ["editor"]),
  i("refresh", "Refresh", "actions", ["core"]),
  i("sync", "Sync", "actions", ["core", "files"]),
  i("save", "Save", "actions", ["core", "files"]),
  i("done", "Done", "actions", ["core"]),
  i("add_circle", "Add circle", "actions", ["core"]),
  i("filter_list", "Filter", "actions", ["core"]),
  i("sort", "Sort", "actions", ["core"]),
  i("tune", "Tune", "actions", ["core", "graphics"]),
  i("more_vert", "More vertical", "ui", ["core"]),
  i("more_horiz", "More horizontal", "ui", ["core"]),
  i("favorite", "Favorite", "actions", ["core", "social", "health"]),
  i("star", "Star", "actions", ["core", "social"]),
  i("bookmark", "Bookmark", "actions", ["core"]),
  i("flag", "Flag", "actions", ["core"]),
  i("push_pin", "Pin", "actions", ["core"]),
  i("label", "Label", "actions", ["core"]),
  i("link", "Link", "actions", ["core"]),
  i("open_in_new", "Open in new", "navigation", ["core"]),
  i("login", "Login", "actions", ["core"]),
  i("logout", "Logout", "actions", ["core"]),
  i("undo", "Undo", "actions", ["editor"]),
  i("redo", "Redo", "actions", ["editor"]),
  i("print", "Print", "actions", ["devices"]),
  i("zoom_in", "Zoom in", "actions", ["graphics"]),
  i("zoom_out", "Zoom out", "actions", ["graphics"]),
  i("fullscreen", "Fullscreen", "actions", ["media"]),
  i("fullscreen_exit", "Exit fullscreen", "actions", ["media"]),
  i("shopping_cart", "Cart", "actions", ["finance"]),
  i("credit_card", "Card", "finance", ["finance"]),
  i("rocket_launch", "Launch", "actions", ["core"]),
  i("bolt", "Bolt", "ui", ["graphics"]),
  i("build", "Build", "ui", ["core"]),
  i("extension", "Extension", "ui", ["core"]),
  i("drag_indicator", "Drag", "ui", ["editor"]),
  i("swap_vert", "Swap vertical", "actions", ["navigation"]),
  i("swap_horiz", "Swap horizontal", "actions", ["navigation"]),
  i("north", "North", "navigation", ["navigation"]),
  i("south", "South", "navigation", ["navigation"]),
  i("expand", "Expand", "navigation", ["navigation"]),
  i("compress", "Compress", "navigation", ["navigation"]),
  i("qr_code_2", "QR code", "actions", ["core"]),
  i("local_offer", "Offer", "actions", ["finance"]),
  i("arrow_back", "Arrow back", "navigation", ["core", "navigation"]),
  i("arrow_forward", "Arrow forward", "navigation", ["core", "navigation"]),
  i("arrow_upward", "Arrow up", "navigation", ["navigation"]),
  i("arrow_downward", "Arrow down", "navigation", ["navigation"]),
  i("chevron_left", "Chevron left", "navigation", ["navigation"]),
  i("chevron_right", "Chevron right", "navigation", ["core", "navigation"]),
  i("expand_more", "Expand more", "navigation", ["core", "navigation"]),
  i("expand_less", "Expand less", "navigation", ["navigation"]),
  i("first_page", "First page", "navigation", ["navigation"]),
  i("last_page", "Last page", "navigation", ["navigation"]),
  i("subdirectory_arrow_right", "Nested", "navigation", ["navigation"]),
  i("apps", "Apps", "navigation", ["core", "navigation"]),
  i("space_dashboard", "Dashboard", "ui", ["core", "navigation"]),
  i("grid_view", "Grid", "ui", ["core", "navigation"]),
  i("view_list", "List", "ui", ["core", "navigation"]),
  i("view_module", "Modules", "ui", ["navigation"]),
  i("view_quilt", "Quilt", "ui", ["navigation"]),
  i("tab", "Tab", "navigation", ["navigation"]),
  i("near_me", "Near me", "places", ["navigation", "travel"]),
  i("person", "Person", "communication", ["core", "social"]),
  i("person_add", "Add person", "communication", ["social"]),
  i("group", "Group", "communication", ["social"]),
  i("groups", "Groups", "communication", ["social"]),
  i("account_circle", "Account", "communication", ["core"]),
  i("manage_accounts", "Manage accounts", "ui", ["core"]),
  i("mail", "Mail", "communication", ["core"]),
  i("chat", "Chat", "communication", ["core", "social"]),
  i("forum", "Forum", "communication", ["social"]),
  i("send", "Send", "communication", ["core"]),
  i("notifications", "Notifications", "communication", ["core"]),
  i("notifications_off", "Notifications off", "communication", ["core"]),
  i("call", "Call", "communication", ["core"]),
  i("videocam", "Video call", "communication", ["media"]),
  i("alternate_email", "Mention", "communication", ["social"]),
  i("contacts", "Contacts", "communication", ["social"]),
  i("inbox", "Inbox", "communication", ["files"]),
  i("drafts", "Drafts", "communication", ["files"]),
  i("sms", "SMS", "communication", ["social"]),
  i("campaign", "Campaign", "social", ["social"]),
  i("support_agent", "Support", "communication", ["core"]),
  i("play_arrow", "Play", "media", ["core", "media"]),
  i("pause", "Pause", "media", ["media"]),
  i("stop", "Stop", "media", ["media"]),
  i("skip_next", "Skip next", "media", ["media"]),
  i("skip_previous", "Skip previous", "media", ["media"]),
  i("fast_forward", "Fast forward", "media", ["media"]),
  i("fast_rewind", "Rewind", "media", ["media"]),
  i("replay", "Replay", "media", ["media"]),
  i("volume_up", "Volume", "media", ["media"]),
  i("volume_down", "Volume down", "media", ["media"]),
  i("volume_off", "Mute", "media", ["media"]),
  i("mic", "Mic", "media", ["media"]),
  i("mic_off", "Mic off", "media", ["media"]),
  i("image", "Image", "media", ["media", "graphics"]),
  i("photo_camera", "Camera", "media", ["media", "devices"]),
  i("photo_library", "Library", "media", ["media"]),
  i("movie", "Movie", "media", ["media"]),
  i("music_note", "Music", "media", ["media"]),
  i("headphones", "Headphones", "media", ["media", "devices"]),
  i("equalizer", "Equalizer", "media", ["media", "graphics"]),
  i("album", "Album", "media", ["media"]),
  i("playlist_play", "Playlist", "media", ["media"]),
  i("shuffle", "Shuffle", "media", ["media"]),
  i("repeat", "Repeat", "media", ["media"]),
  i("closed_caption", "Captions", "media", ["media"]),
  i("fiber_manual_record", "Record", "media", ["media"]),
  i("podcasts", "Podcasts", "media", ["media"]),
  i("location_on", "Location", "places", ["travel", "navigation"]),
  i("map", "Map", "places", ["travel"]),
  i("explore", "Explore", "places", ["travel", "navigation"]),
  i("public", "Public", "places", ["social", "travel"]),
  i("flight", "Flight", "places", ["travel"]),
  i("hotel", "Hotel", "places", ["travel"]),
  i("restaurant", "Restaurant", "places", ["travel"]),
  i("local_cafe", "Cafe", "places", ["travel"]),
  i("directions_car", "Car", "places", ["travel"]),
  i("directions_bus", "Bus", "places", ["travel"]),
  i("directions_bike", "Bike", "places", ["travel"]),
  i("directions_walk", "Walk", "places", ["travel"]),
  i("train", "Train", "places", ["travel"]),
  i("local_taxi", "Taxi", "places", ["travel"]),
  i("two_wheeler", "Scooter", "places", ["travel"]),
  i("sailing", "Sailing", "places", ["travel"]),
  i("hiking", "Hiking", "places", ["travel", "health"]),
  i("park", "Park", "places", ["travel"]),
  i("beach_access", "Beach", "places", ["travel"]),
  i("pool", "Pool", "places", ["travel", "health"]),
  i("work", "Work", "places", ["core"]),
  i("school", "School", "places", ["core"]),
  i("apartment", "Apartment", "places", ["travel"]),
  i("storefront", "Store", "places", ["finance"]),
  i("local_mall", "Mall", "places", ["finance"]),
  i("local_grocery_store", "Grocery", "places", ["travel"]),
  i("local_gas_station", "Gas", "places", ["travel"]),
  i("ev_station", "EV station", "places", ["travel"]),
  i("luggage", "Luggage", "places", ["travel"]),
  i("info", "Info", "ui", ["core"]),
  i("warning", "Warning", "ui", ["core"]),
  i("error", "Error", "ui", ["core"]),
  i("help", "Help", "ui", ["core"]),
  i("palette", "Palette", "ui", ["graphics"]),
  i("color_lens", "Color lens", "ui", ["graphics"]),
  i("brush", "Brush", "ui", ["graphics", "editor"]),
  i("code", "Code", "ui", ["core", "editor"]),
  i("android", "Android", "ui", ["core", "devices"]),
  i("language", "Language", "ui", ["core"]),
  i("dark_mode", "Dark mode", "ui", ["core", "graphics"]),
  i("light_mode", "Light mode", "ui", ["core", "graphics"]),
  i("contrast", "Contrast", "ui", ["graphics"]),
  i("widgets", "Widgets", "ui", ["core"]),
  i("visibility", "Visibility", "ui", ["core"]),
  i("visibility_off", "Visibility off", "ui", ["core"]),
  i("lock", "Lock", "ui", ["core"]),
  i("lock_open", "Lock open", "ui", ["core"]),
  i("calendar_today", "Calendar", "ui", ["core"]),
  i("schedule", "Schedule", "ui", ["core"]),
  i("science", "Science", "ui", ["core"]),
  i("layers", "Layers", "ui", ["graphics", "editor"]),
  i("token", "Token", "ui", ["core"]),
  i("styler", "Styler", "ui", ["graphics"]),
  i("interests", "Interests", "ui", ["core"]),
  i("wifi", "Wifi", "ui", ["devices"]),
  i("bluetooth", "Bluetooth", "ui", ["devices"]),
  i("battery_full", "Battery", "ui", ["devices"]),
  i("battery_charging_full", "Charging", "devices", ["devices"]),
  i("signal_cellular_alt", "Signal", "ui", ["devices"]),
  i("gps_fixed", "GPS", "ui", ["travel"]),
  i("airplanemode_active", "Airplane", "ui", ["travel"]),
  i("do_not_disturb_on", "DND", "ui", ["core"]),
  i("smartphone", "Smartphone", "ui", ["devices"]),
  i("tablet_mac", "Tablet", "ui", ["devices"]),
  i("desktop_windows", "Desktop", "ui", ["devices"]),
  i("terminal", "Terminal", "ui", ["core"]),
  i("cloud", "Cloud", "ui", ["files"]),
  i("cloud_off", "Cloud off", "ui", ["files"]),
  i("cloud_sync", "Cloud sync", "ui", ["files"]),
  i("security", "Security", "ui", ["core"]),
  i("verified", "Verified", "ui", ["social"]),
  i("key", "Key", "ui", ["core"]),
  i("fingerprint", "Fingerprint", "ui", ["devices"]),
  i("face", "Face", "ui", ["devices"]),
  i("password", "Password", "ui", ["core"]),
  i("admin_panel_settings", "Admin", "ui", ["core"]),
  i("construction", "Construction", "ui", ["core"]),
  i("handyman", "Handyman", "ui", ["core"]),
  i("font_download", "Font download", "ui", ["editor"]),
  i("title", "Title", "ui", ["editor"]),
  i("search_off", "Search off", "actions", ["core"]),
  i("sunny", "Sunny", "weather", ["weather"]),
  i("partly_cloudy_day", "Partly cloudy", "weather", ["weather"]),
  i("cloud_queue", "Cloudy", "weather", ["weather"]),
  i("rainy", "Rainy", "weather", ["weather"]),
  i("thunderstorm", "Thunderstorm", "weather", ["weather"]),
  i("weather_snowy", "Snow", "weather", ["weather"]),
  i("ac_unit", "Cold", "weather", ["weather"]),
  i("air", "Wind", "weather", ["weather"]),
  i("water_drop", "Drop", "weather", ["weather", "health"]),
  i("cyclone", "Cyclone", "weather", ["weather"]),
  i("foggy", "Fog", "weather", ["weather"]),
  i("nightlight", "Night", "weather", ["weather", "graphics"]),
  i("wb_twilight", "Twilight", "weather", ["weather", "graphics"]),
  i("thermostat", "Thermostat", "weather", ["weather", "devices"]),
  i("water", "Water", "weather", ["weather"]),
  i("waves", "Waves", "weather", ["weather", "graphics"]),
  i("laptop", "Laptop", "devices", ["devices"]),
  i("computer", "Computer", "devices", ["devices"]),
  i("keyboard", "Keyboard", "devices", ["devices"]),
  i("mouse", "Mouse", "devices", ["devices"]),
  i("memory", "Memory", "devices", ["devices"]),
  i("developer_board", "Board", "devices", ["devices"]),
  i("router", "Router", "devices", ["devices"]),
  i("watch", "Watch", "devices", ["devices"]),
  i("speaker", "Speaker", "devices", ["devices", "media"]),
  i("tv", "TV", "devices", ["devices", "media"]),
  i("videogame_asset", "Gamepad", "devices", ["devices"]),
  i("usb", "USB", "devices", ["devices"]),
  i("sd_card", "SD card", "devices", ["devices"]),
  i("power", "Power", "devices", ["devices"]),
  i("flashlight_on", "Flashlight", "devices", ["devices"]),
  i("devices", "Devices", "devices", ["devices"]),
  i("format_bold", "Bold", "editor", ["editor"]),
  i("format_italic", "Italic", "editor", ["editor"]),
  i("format_underlined", "Underline", "editor", ["editor"]),
  i("format_align_left", "Align left", "editor", ["editor"]),
  i("format_align_center", "Align center", "editor", ["editor"]),
  i("format_align_right", "Align right", "editor", ["editor"]),
  i("format_list_bulleted", "Bullets", "editor", ["editor"]),
  i("format_list_numbered", "Numbers", "editor", ["editor"]),
  i("format_quote", "Quote", "editor", ["editor"]),
  i("format_size", "Type size", "editor", ["editor"]),
  i("format_color_text", "Text color", "editor", ["editor", "graphics"]),
  i("format_paint", "Paint", "editor", ["editor", "graphics"]),
  i("notes", "Notes", "editor", ["editor", "files"]),
  i("spellcheck", "Spellcheck", "editor", ["editor"]),
  i("find_in_page", "Find", "editor", ["editor"]),
  i("draw", "Draw", "editor", ["editor", "graphics"]),
  i("highlight", "Highlight", "editor", ["editor"]),
  i("strikethrough_s", "Strike", "editor", ["editor"]),
  i("table_chart", "Table", "editor", ["editor", "charts"]),
  i("payments", "Payments", "finance", ["finance"]),
  i("account_balance", "Bank", "finance", ["finance"]),
  i("account_balance_wallet", "Wallet", "finance", ["finance"]),
  i("trending_up", "Trending up", "finance", ["finance", "charts"]),
  i("trending_down", "Trending down", "finance", ["finance", "charts"]),
  i("savings", "Savings", "finance", ["finance"]),
  i("attach_money", "Money", "finance", ["finance"]),
  i("currency_bitcoin", "Bitcoin", "finance", ["finance"]),
  i("currency_exchange", "Exchange", "finance", ["finance"]),
  i("receipt_long", "Receipt", "finance", ["finance"]),
  i("request_quote", "Quote", "finance", ["finance"]),
  i("analytics", "Analytics", "charts", ["charts", "finance"]),
  i("pie_chart", "Pie", "charts", ["charts"]),
  i("bar_chart", "Bar", "charts", ["charts"]),
  i("show_chart", "Line", "charts", ["charts"]),
  i("stacked_bar_chart", "Stacked", "charts", ["charts"]),
  i("candlestick_chart", "Candles", "charts", ["charts"]),
  i("scatter_plot", "Scatter", "charts", ["charts"]),
  i("monetization_on", "Coin", "finance", ["finance"]),
  i("paid", "Paid", "finance", ["finance"]),
  i("monitor_heart", "Heart monitor", "health", ["health"]),
  i("local_hospital", "Hospital", "health", ["health"]),
  i("medical_services", "Medical", "health", ["health"]),
  i("medication", "Medication", "health", ["health"]),
  i("fitness_center", "Fitness", "health", ["health"]),
  i("self_improvement", "Wellbeing", "health", ["health"]),
  i("spa", "Spa", "health", ["health"]),
  i("psychology", "Mind", "health", ["health"]),
  i("sentiment_satisfied", "Satisfied", "health", ["health", "social"]),
  i("sentiment_dissatisfied", "Dissatisfied", "health", ["health", "social"]),
  i("bedtime", "Bedtime", "health", ["health"]),
  i("health_and_safety", "Safety", "health", ["health"]),
  i("emergency", "Emergency", "health", ["health"]),
  i("vaccines", "Vaccines", "health", ["health"]),
  i("accessibility", "Accessibility", "health", ["health", "core"]),
  i("accessible", "Accessible", "health", ["health"]),
  i("hearing", "Hearing", "health", ["health"]),
  i("folder", "Folder", "files", ["files", "core"]),
  i("folder_open", "Folder open", "files", ["files"]),
  i("folder_zip", "Archive", "files", ["files"]),
  i("description", "Document", "files", ["files", "core"]),
  i("article", "Article", "files", ["files"]),
  i("picture_as_pdf", "PDF", "files", ["files"]),
  i("upload_file", "Upload file", "files", ["files"]),
  i("attach_file", "Attach", "files", ["files"]),
  i("snippet_folder", "Snippets", "files", ["files"]),
  i("dataset", "Dataset", "files", ["files", "charts"]),
  i("table_view", "Table view", "files", ["files", "charts"]),
  i("schema", "Schema", "files", ["files"]),
  i("cloud_upload", "Cloud upload", "files", ["files"]),
  i("cloud_download", "Cloud download", "files", ["files"]),
  i("thumb_up", "Thumb up", "social", ["social"]),
  i("thumb_down", "Thumb down", "social", ["social"]),
  i("comment", "Comment", "social", ["social"]),
  i("rss_feed", "RSS", "social", ["social"]),
  i("diversity_3", "Community", "social", ["social"]),
  i("handshake", "Handshake", "social", ["social"]),
  i("volunteer_activism", "Volunteer", "social", ["social", "health"]),
  i("translate", "Translate", "social", ["social"]),
  i("ios_share", "Share sheet", "social", ["social"]),
  i("reviews", "Reviews", "social", ["social"]),
  i("rate_review", "Rate", "social", ["social"]),
  i("emoji_emotions", "Emoji", "social", ["social"]),
  i("celebration", "Celebration", "social", ["social"]),
  i("cake", "Cake", "social", ["social"]),
  i("card_giftcard", "Gift", "social", ["social", "finance"]),
  i("gradient", "Gradient", "ui", ["graphics"]),
  i("texture", "Texture", "ui", ["graphics"]),
  i("blur_on", "Blur", "ui", ["graphics"]),
  i("auto_awesome", "Sparkle", "ui", ["graphics"]),
  i("filter_vintage", "Vintage", "ui", ["graphics"]),
  i("tonality", "Tonality", "ui", ["graphics"]),
  i("brightness_6", "Brightness", "ui", ["graphics"]),
  i("hdr_strong", "HDR", "ui", ["graphics"]),
  i("grain", "Grain", "ui", ["graphics"]),
  i("animation", "Animation", "ui", ["graphics"]),
  i("view_in_ar", "AR", "ui", ["graphics"]),
  i("filter", "Filter FX", "ui", ["graphics"]),
  i("filter_b_and_w", "Mono", "ui", ["graphics"]),
  i("filter_drama", "Drama", "ui", ["graphics"]),
  i("lens_blur", "Lens blur", "ui", ["graphics"]),
  i("deblur", "Deblur", "ui", ["graphics"]),
  i("colorize", "Colorize", "ui", ["graphics"]),
  i("invert_colors", "Invert", "ui", ["graphics"]),
  i("opacity", "Opacity", "ui", ["graphics"]),
  i("hue", "Hue", "ui", ["graphics"]),
  i("flare", "Flare", "ui", ["graphics"]),
  i("flash_on", "Flash", "ui", ["graphics"]),
  i("exposure", "Exposure", "ui", ["graphics"]),
  i("wb_iridescent", "Iridescent", "ui", ["graphics"]),
  i("crop", "Crop", "editor", ["graphics", "editor"]),
  i("crop_rotate", "Rotate crop", "editor", ["graphics"]),
  i("flip", "Flip", "editor", ["graphics"]),
  i("rotate_right", "Rotate", "editor", ["graphics"]),
  i("transform", "Transform", "editor", ["graphics"]),
  i("architecture", "Architecture", "ui", ["graphics"]),
  i("square_foot", "Measure", "ui", ["graphics"]),
  i("hexagon", "Hexagon", "ui", ["graphics"]),
  i("pentagon", "Pentagon", "ui", ["graphics"]),
  i("category", "Category", "ui", ["graphics"]),
  i("grid_4x4", "Grid 4×4", "ui", ["graphics"]),
  i("hide_image", "Hide image", "media", ["graphics"]),
  i("shutter_speed", "Shutter", "media", ["graphics"]),
  i("radio_button_unchecked", "Radio off", "ui", ["core"]),
  i("radio_button_checked", "Radio on", "ui", ["core"]),
];

export const ICON_CATEGORIES: { id: IconCategory | "all"; label: string }[] = [
  { id: "all", label: "All" },
  { id: "actions", label: "Actions" },
  { id: "navigation", label: "Navigation" },
  { id: "communication", label: "Communication" },
  { id: "media", label: "Media" },
  { id: "places", label: "Places" },
  { id: "weather", label: "Weather" },
  { id: "devices", label: "Devices" },
  { id: "editor", label: "Editor" },
  { id: "finance", label: "Finance" },
  { id: "health", label: "Health" },
  { id: "files", label: "Files" },
  { id: "social", label: "Social" },
  { id: "charts", label: "Charts" },
  { id: "ui", label: "System" },
];

export function iconCompose(name: string, style: MdIconStyle = "outlined") {
  return composeIconName(name, style);
}

export function packIcons(pack: IconPackId) {
  return ICONS.filter((icon) => icon.packs.includes(pack));
}

export function iconsKotlinObject(style: MdIconStyle = "outlined") {
  const lines = ICONS.map(
    (icon) => `    val ${kotlinIdent(icon.name)} = "${icon.name}"`,
  );
  return `package com.britta.design

object BrittaIcons {
    const val STYLE = "${style}"
${lines.join("\n")}
}
`;
}

function kotlinIdent(name: string) {
  const pascal = name
    .split("_")
    .map((p) => (p ? p[0]!.toUpperCase() + p.slice(1) : p))
    .join("");
  return pascal[0]!.toLowerCase() + pascal.slice(1);
}

export function iconsJson(pack?: IconPackId) {
  const list = pack ? packIcons(pack) : ICONS;
  return JSON.stringify(
    {
      family: "Material Symbols",
      axes: { fill: [0, 1], weight: [100, 700], grade: [-25, 200], opsz: [20, 48] },
      styles: ["outlined", "rounded", "sharp"],
      pack: pack ?? "all",
      icons: list.map((icon) => ({
        name: icon.name,
        label: icon.label,
        category: icon.category,
        packs: icon.packs,
        compose: iconCompose(icon.name),
      })),
    },
    null,
    2,
  );
}
