export type UtilityKind = "color" | "space" | "radius" | "type" | "layout" | "motion" | "shade";

export type UtilityItem = {
  className: string;
  css: string;
  compose: string;
  kind: UtilityKind;
  preview?: string;
};

export const UTILITY_GROUPS: { id: UtilityKind | "all"; label: string }[] = [
  { id: "all", label: "All" },
  { id: "color", label: "Color" },
  { id: "space", label: "Spacing" },
  { id: "radius", label: "Radius" },
  { id: "type", label: "Type" },
  { id: "layout", label: "Layout" },
  { id: "motion", label: "Motion" },
  { id: "shade", label: "Shading" },
];

export const UTILITIES: UtilityItem[] = [
  { className: "bg-primary", css: "background: var(--md-primary)", compose: "Modifier.background(scheme.primary)", kind: "color", preview: "var(--md-primary)" },
  { className: "text-on-primary", css: "color: var(--md-on-primary)", compose: "color = scheme.onPrimary", kind: "color" },
  { className: "bg-primary-container", css: "background: var(--md-primary-container)", compose: "Modifier.background(scheme.primaryContainer)", kind: "color", preview: "var(--md-primary-container)" },
  { className: "text-on-primary-container", css: "color: var(--md-on-primary-container)", compose: "color = scheme.onPrimaryContainer", kind: "color" },
  { className: "bg-secondary-container", css: "background: var(--md-secondary-container)", compose: "Modifier.background(scheme.secondaryContainer)", kind: "color", preview: "var(--md-secondary-container)" },
  { className: "text-on-secondary-container", css: "color: var(--md-on-secondary-container)", compose: "color = scheme.onSecondaryContainer", kind: "color" },
  { className: "bg-surface", css: "background: var(--md-surface)", compose: "Modifier.background(scheme.surface)", kind: "color", preview: "var(--md-surface)" },
  { className: "bg-surface-container", css: "background: var(--md-surface-container)", compose: "Modifier.background(scheme.surfaceContainer)", kind: "color", preview: "var(--md-surface-container)" },
  { className: "bg-surface-container-low", css: "background: var(--md-surface-container-low)", compose: "Modifier.background(scheme.surfaceContainerLow)", kind: "color", preview: "var(--md-surface-container-low)" },
  { className: "bg-surface-container-highest", css: "background: var(--md-surface-container-highest)", compose: "Modifier.background(scheme.surfaceContainerHighest)", kind: "color", preview: "var(--md-surface-container-highest)" },
  { className: "text-on-surface", css: "color: var(--md-on-surface)", compose: "color = scheme.onSurface", kind: "color" },
  { className: "text-on-surface-variant", css: "color: var(--md-on-surface-variant)", compose: "color = scheme.onSurfaceVariant", kind: "color" },
  { className: "text-primary", css: "color: var(--md-primary)", compose: "color = scheme.primary", kind: "color" },
  { className: "bg-error", css: "background: var(--md-error)", compose: "Modifier.background(scheme.error)", kind: "color", preview: "var(--md-error)" },
  { className: "text-error", css: "color: var(--md-error)", compose: "color = scheme.error", kind: "color" },
  { className: "ring-outline-variant", css: "box-shadow: 0 0 0 1px var(--md-outline-variant)", compose: "BorderStroke(1.dp, scheme.outlineVariant)", kind: "color" },
  { className: "p-xs", css: "padding: 4px", compose: "Modifier.padding(BrittaGeneratedSpacing.xs)", kind: "space" },
  { className: "p-sm", css: "padding: 8px", compose: "Modifier.padding(BrittaGeneratedSpacing.sm)", kind: "space" },
  { className: "p-md", css: "padding: 16px", compose: "Modifier.padding(BrittaGeneratedSpacing.md)", kind: "space" },
  { className: "p-lg", css: "padding: 24px", compose: "Modifier.padding(BrittaGeneratedSpacing.lg)", kind: "space" },
  { className: "p-xl", css: "padding: 32px", compose: "Modifier.padding(BrittaGeneratedSpacing.xl)", kind: "space" },
  { className: "p-2xl", css: "padding: 48px", compose: "Modifier.padding(BrittaGeneratedSpacing.xxl)", kind: "space" },
  { className: "px-md", css: "padding-inline: 16px", compose: "Modifier.padding(horizontal = BrittaGeneratedSpacing.md)", kind: "space" },
  { className: "py-sm", css: "padding-block: 8px", compose: "Modifier.padding(vertical = BrittaGeneratedSpacing.sm)", kind: "space" },
  { className: "gap-sm", css: "gap: 8px", compose: "Arrangement.spacedBy(BrittaGeneratedSpacing.sm)", kind: "space" },
  { className: "gap-md", css: "gap: 16px", compose: "Arrangement.spacedBy(BrittaGeneratedSpacing.md)", kind: "space" },
  { className: "gap-lg", css: "gap: 24px", compose: "Arrangement.spacedBy(BrittaGeneratedSpacing.lg)", kind: "space" },
  { className: "m-md", css: "margin: 16px", compose: "Modifier.padding is preferred; Spacer(16.dp)", kind: "space" },
  { className: "rounded-xs", css: "border-radius: 4px", compose: "RoundedCornerShape(BrittaGeneratedRadius.xs)", kind: "radius" },
  { className: "rounded-sm", css: "border-radius: 8px", compose: "RoundedCornerShape(BrittaGeneratedRadius.sm)", kind: "radius" },
  { className: "rounded-md", css: "border-radius: 12px", compose: "RoundedCornerShape(BrittaGeneratedRadius.md)", kind: "radius" },
  { className: "rounded-lg", css: "border-radius: 16px", compose: "RoundedCornerShape(BrittaGeneratedRadius.lg)", kind: "radius" },
  { className: "rounded-xl", css: "border-radius: 28px", compose: "RoundedCornerShape(BrittaGeneratedRadius.xl)", kind: "radius" },
  { className: "rounded-full", css: "border-radius: 9999px", compose: "CircleShape / RoundedCornerShape(50%)", kind: "radius" },
  { className: "text-display-large", css: "font-size: 57px / 64px", compose: "BrittaGeneratedTypography.displayLarge", kind: "type" },
  { className: "text-headline-large", css: "font-size: 32px / 40px", compose: "BrittaGeneratedTypography.headlineLarge", kind: "type" },
  { className: "text-headline-medium", css: "font-size: 28px / 36px", compose: "BrittaGeneratedTypography.headlineMedium", kind: "type" },
  { className: "text-title-large", css: "font-size: 22px / 28px", compose: "BrittaGeneratedTypography.titleLarge", kind: "type" },
  { className: "text-title-medium", css: "font-size: 16px / 24px", compose: "BrittaGeneratedTypography.titleMedium", kind: "type" },
  { className: "text-body-large", css: "font-size: 16px / 24px", compose: "BrittaGeneratedTypography.bodyLarge", kind: "type" },
  { className: "text-body-medium", css: "font-size: 14px / 20px", compose: "BrittaGeneratedTypography.bodyMedium", kind: "type" },
  { className: "text-label-large", css: "font-size: 14px / 20px", compose: "BrittaGeneratedTypography.labelLarge", kind: "type" },
  { className: "text-label-medium", css: "font-size: 12px / 16px", compose: "BrittaGeneratedTypography.labelMedium", kind: "type" },
  { className: "font-sans", css: "font-family: Inter", compose: "FontFamily(GoogleFont(\"Inter\"))", kind: "type" },
  { className: "font-display", css: "font-family: Outfit", compose: "FontFamily(GoogleFont(\"Outfit\"))", kind: "type" },
  { className: "font-mono", css: "font-family: JetBrains Mono", compose: "FontFamily(GoogleFont(\"JetBrains Mono\"))", kind: "type" },
  { className: "flex", css: "display: flex", compose: "Row { }", kind: "layout" },
  { className: "flex-col", css: "flex-direction: column", compose: "Column { }", kind: "layout" },
  { className: "items-center", css: "align-items: center", compose: "verticalAlignment = Alignment.CenterVertically", kind: "layout" },
  { className: "justify-center", css: "justify-content: center", compose: "horizontalArrangement = Arrangement.Center", kind: "layout" },
  { className: "justify-between", css: "justify-content: space-between", compose: "horizontalArrangement = Arrangement.SpaceBetween", kind: "layout" },
  { className: "grid", css: "display: grid", compose: "LazyVerticalGrid / FlowRow", kind: "layout" },
  { className: "w-full", css: "width: 100%", compose: "Modifier.fillMaxWidth()", kind: "layout" },
  { className: "h-full", css: "height: 100%", compose: "Modifier.fillMaxHeight()", kind: "layout" },
  { className: "min-h-10", css: "min-height: 40px", compose: "Modifier.heightIn(min = 40.dp)", kind: "layout" },
  { className: "overflow-hidden", css: "overflow: hidden", compose: "Modifier.clip(shape)", kind: "layout" },
  { className: "duration-short", css: "transition-duration: 150ms", compose: "tween(150)", kind: "motion" },
  { className: "duration-medium", css: "transition-duration: 250ms", compose: "tween(250)", kind: "motion" },
  { className: "duration-long", css: "transition-duration: 400ms", compose: "tween(400)", kind: "motion" },
  { className: "ease-standard", css: "cubic-bezier(0.2, 0, 0, 1)", compose: "FastOutSlowInEasing", kind: "motion" },
  { className: "ease-emphasized", css: "cubic-bezier(0.05, 0.7, 0.1, 1)", compose: "EmphasizedEasing", kind: "motion" },
  { className: "shadow-elev-1", css: "box-shadow: var(--shadow-elev-1)", compose: "BrittaElevation.level1", kind: "shade" },
  { className: "shadow-elev-2", css: "box-shadow: var(--shadow-elev-2)", compose: "BrittaElevation.level2", kind: "shade" },
  { className: "shadow-elev-3", css: "box-shadow: var(--shadow-elev-3)", compose: "BrittaElevation.level3", kind: "shade" },
  { className: "shadow-elev-5", css: "box-shadow: var(--shadow-elev-5)", compose: "BrittaElevation.level5", kind: "shade" },
  { className: "shade-key", css: "linear-gradient from surface-tint 8%", compose: "BrittaShade.Key", kind: "shade" },
  { className: "bg-grain", css: "paper-grain shader overlay", compose: "BrittaShaders.PAPER_GRAIN", kind: "shade" },
];

export const DEFAULT_PLAYGROUND = [
  "bg-primary-container",
  "text-on-primary-container",
  "p-lg",
  "rounded-lg",
  "font-display",
  "text-title-large",
];
