/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AndroidRouteImport } from './routes/android'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as FontsRouteImport } from './routes/fonts'
import { Route as IconsRouteImport } from './routes/icons'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as ShadersRouteImport } from './routes/shaders'
import { Route as StartRouteImport } from './routes/start'
import { Route as ThemeRouteImport } from './routes/theme'
import { Route as TokensRouteImport } from './routes/tokens'
import { Route as UtilitiesRouteImport } from './routes/utilities'
import { Route as ComponentsIndexRouteImport } from './routes/components.index'
import { Route as ComponentsSlugRouteImport } from './routes/components.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AndroidRoute = AndroidRouteImport.update({
  id: '/android',
  path: '/android',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const FontsRoute = FontsRouteImport.update({
  id: '/fonts',
  path: '/fonts',
  getParentRoute: () => rootRouteImport,
} as any)
const IconsRoute = IconsRouteImport.update({
  id: '/icons',
  path: '/icons',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const ShadersRoute = ShadersRouteImport.update({
  id: '/shaders',
  path: '/shaders',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemeRoute = ThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensRoute = TokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilitiesRoute = UtilitiesRouteImport.update({
  id: '/utilities',
  path: '/utilities',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsSlugRoute = ComponentsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ComponentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/android': typeof AndroidRoute
  '/components': typeof ComponentsRouteWithChildren
  '/fonts': typeof FontsRoute
  '/icons': typeof IconsRoute
  '/playground': typeof PlaygroundRoute
  '/shaders': typeof ShadersRoute
  '/start': typeof StartRoute
  '/theme': typeof ThemeRoute
  '/tokens': typeof TokensRoute
  '/utilities': typeof UtilitiesRoute
  '/components/$slug': typeof ComponentsSlugRoute
  '/components/': typeof ComponentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/android': typeof AndroidRoute
  '/fonts': typeof FontsRoute
  '/icons': typeof IconsRoute
  '/playground': typeof PlaygroundRoute
  '/shaders': typeof ShadersRoute
  '/start': typeof StartRoute
  '/theme': typeof ThemeRoute
  '/tokens': typeof TokensRoute
  '/utilities': typeof UtilitiesRoute
  '/components/$slug': typeof ComponentsSlugRoute
  '/components': typeof ComponentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/android': typeof AndroidRoute
  '/components': typeof ComponentsRouteWithChildren
  '/fonts': typeof FontsRoute
  '/icons': typeof IconsRoute
  '/playground': typeof PlaygroundRoute
  '/shaders': typeof ShadersRoute
  '/start': typeof StartRoute
  '/theme': typeof ThemeRoute
  '/tokens': typeof TokensRoute
  '/utilities': typeof UtilitiesRoute
  '/components/$slug': typeof ComponentsSlugRoute
  '/components/': typeof ComponentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/android'
    | '/components'
    | '/fonts'
    | '/icons'
    | '/playground'
    | '/shaders'
    | '/start'
    | '/theme'
    | '/tokens'
    | '/utilities'
    | '/components/$slug'
    | '/components/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/android'
    | '/fonts'
    | '/icons'
    | '/playground'
    | '/shaders'
    | '/start'
    | '/theme'
    | '/tokens'
    | '/utilities'
    | '/components/$slug'
    | '/components'
  id:
    | '__root__'
    | '/'
    | '/android'
    | '/components'
    | '/fonts'
    | '/icons'
    | '/playground'
    | '/shaders'
    | '/start'
    | '/theme'
    | '/tokens'
    | '/utilities'
    | '/components/$slug'
    | '/components/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AndroidRoute: typeof AndroidRoute
  ComponentsRoute: typeof ComponentsRouteWithChildren
  FontsRoute: typeof FontsRoute
  IconsRoute: typeof IconsRoute
  PlaygroundRoute: typeof PlaygroundRoute
  ShadersRoute: typeof ShadersRoute
  StartRoute: typeof StartRoute
  ThemeRoute: typeof ThemeRoute
  TokensRoute: typeof TokensRoute
  UtilitiesRoute: typeof UtilitiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/android': {
      id: '/android'
      path: '/android'
      fullPath: '/android'
      preLoaderRoute: typeof AndroidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fonts': {
      id: '/fonts'
      path: '/fonts'
      fullPath: '/fonts'
      preLoaderRoute: typeof FontsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/icons': {
      id: '/icons'
      path: '/icons'
      fullPath: '/icons'
      preLoaderRoute: typeof IconsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shaders': {
      id: '/shaders'
      path: '/shaders'
      fullPath: '/shaders'
      preLoaderRoute: typeof ShadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theme': {
      id: '/theme'
      path: '/theme'
      fullPath: '/theme'
      preLoaderRoute: typeof ThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens': {
      id: '/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof TokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilities': {
      id: '/utilities'
      path: '/utilities'
      fullPath: '/utilities'
      preLoaderRoute: typeof UtilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/$slug': {
      id: '/components/$slug'
      path: '/$slug'
      fullPath: '/components/$slug'
      preLoaderRoute: typeof ComponentsSlugRouteImport
      parentRoute: typeof ComponentsRoute
    }
  }
}

interface ComponentsRouteChildren {
  ComponentsSlugRoute: typeof ComponentsSlugRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
}

const ComponentsRouteChildren: ComponentsRouteChildren = {
  ComponentsSlugRoute: ComponentsSlugRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
}

const ComponentsRouteWithChildren = ComponentsRoute._addFileChildren(
  ComponentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AndroidRoute: AndroidRoute,
  ComponentsRoute: ComponentsRouteWithChildren,
  FontsRoute: FontsRoute,
  IconsRoute: IconsRoute,
  PlaygroundRoute: PlaygroundRoute,
  ShadersRoute: ShadersRoute,
  StartRoute: StartRoute,
  ThemeRoute: ThemeRoute,
  TokensRoute: TokensRoute,
  UtilitiesRoute: UtilitiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
